--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Abi2005/EntityForm
build-by-default: true
branches:
- master
projects:
  EntityForm:
    path: ""
    model: virion
    type: library
...
